### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by derwin12** [ZEPL/kafka-twitter#2]
Installing on Ubuntu
Oracle Java 1.8

./gradlew run -Pargs="/u01/software/kafka-twitter/conf/producer.conf" -Dhttp.proxyHost=proxy.xxx -Dhttp.proxyPort=80
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
/u01/software/kafka-twitter/src/main/java/com/nflabs/peloton2/kafka/producer/TwitterProducer.java:71: error: local variable context is accessed from within inner class; needs to be declared final
                    KeyedMessage<String, String> data = new KeyedMessage<String, String>(context.getString(TwitterSourceConstant.KAFKA_TOPIC)

Going to dig into the code but if someone has the quick answer that would be appreciated.

**Comment by SyedJameer** [comment]
Total time: 6.096 secs
trainings@system6:~/Desktop/testing/kafka-twitter-master$ cd ..
trainings@system6:~/Desktop/testing$ ./gradlew run -Pargs="/u01/software/kafka-twitter/conf/producer.conf" -Dhttp.proxyHost=proxy.xxx -Dhttp.proxyPort=80
bash: ./gradlew: No such file or directory
trainings@system6:~/Desktop/testing$ cd kafka-twitter-master/
trainings@system6:~/Desktop/testing/kafka-twitter-master$ ./gradlew run -Pargs="/u01/software/kafka-twitter/conf/producer.conf" -Dhttp.proxyHost=proxy.xxx -Dhttp.proxyPort=80
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not find org.twitter4j:twitter4j-stream:4.0.2.
  Required by:
      :kafka-twitter-master:0.0.1
> Could not resolve junit:junit:3.8.1.
  Required by:
      :kafka-twitter-master:0.0.1 > org.apache.kafka:kafka_2.10:0.8.0 > org.apache.zookeeper:zookeeper:3.3.4 > jline:jline:0.9.94
   > Could not parse POM /home/trainings/.m2/repository/junit/junit/3.8.1/junit-3.8.1.pom
      > project must be the root tag

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by SyedJameer** [comment]
can any one tell how to run this project in gradle in linux terminal
